services:
    keycloak:
      image: quay.io/keycloak/keycloak:26.5.1
      environment:
        # 数据库配置
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://192.168.1.25:5432/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: keycloak

        # 管理员账号
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin

        # 生产模式
        KC_HOSTNAME: localhost
        KC_HTTP_ENABLED: "true"

      ports:
        - "8080:8080"

      command: start

      restart: unless-stopped